# My first attempt to write a notebook

Simon Mathias, Department of Engineering, Durham University

## Learning outcomes

* Input data into a 1D array.
* Access data from a 1D array.
* Distinguish between row and column vectors.
* Determine the size of an array.
* Input data into 2D arrays.
* Access data from 2D arrays.
* Write a script file.
* Import data from an excel file.
* Plot data in x-y scatter plots.

## Input data into a 1D array

First of we will import `numpy` and make an array.

In [91]:
#Import the numpy package
import numpy as np
#Make an array A=[4 6 8 5 1 3 2]
A=np.array([4, 6, 8, 5, 1, 3, 2])
#Display the array
print(A)

[4 6 8 5 1 3 2]


Now we will have a go at doing some basic arithmetic.

In [92]:
#Perform some arithmetic
B=A*2
C=A+2
print(B)
print(C)

[ 8 12 16 10  2  6  4]
[ 6  8 10  7  3  5  4]


## Access data from a 1D array

He we will have a got at extracting some columns from the array.

In [93]:
#Extract the third column of A and store it in B
B=A[2]
#Extract the fith column of A and store it in C
C=A[4]
#Extract both third and fifth columns and store in D
D=A[[2,4]]
#Now let's print the results
print(B)
print(C)
print(D)
#More commands
print(np.sin(5))
print(6*(4+3))

8
1
[8 1]
-0.9589242746631385
42


The square brackets, `[]`, can be used for stacking values in arrays. Curved brackets, `()`, can be used for specifying functional arguments or performing bracketed arithmetic, e.g.

In [94]:
#More commands
print(np.sin(5))
print(6*(4+3))

-0.9589242746631385
42


Interestingly, typing `np.arange(2,6,1)` produces a sequence of numbers from 2 to 5 in increments of 1.

In [95]:
C=np.arange(2,6,1)
print(C)

[2 3 4 5]


The above functionality can be used to more easily obtain multiple values from a vector. For example:

In [96]:
print(A[np.arange(2,6,1)])

[8 5 1 3]


Above we were able to extract the 3rd, 4th, 5th and 6th data points from A. These are now stored in a vector called B. Note that the 3rd data point is located at the 2. This is because Python starts at zero (for comparison, MATLAB starts at 1).

Note that `np.arange(2,8,1)` produced a sequence of numbers from 2 to 7 in increments of 1. `np.arange(2,8,2)` produces a similar sequence but in increments of 2.

In [97]:
print(np.arange(2,8,1))

[2 3 4 5 6 7]


In [98]:
print(np.arange(2,8,2))

[2 4 6]


Observe that the sequence does not include 7 as this does not fit within the specified sequence.

The above can be useful if one wants to extract every other number from a vector. For example:

In [99]:
B=A[np.arange(0,7,2)]
print(B)

[4 8 1 2]


In [100]:
C=A[np.arange(1,7,2)]
print(C)

[6 5 3]


Above it can be seen that B now contains the 1st, 3rd, 5th and 7th numbers from A while C contains the 2nd, 4th and 6th numbers from A.

Note that `np.arange(1,7,2)` would produce a sequence in increments of 3 etc.

## Row vectors and column vectors

All the arrays we have studied so far are 1D arrays. But if you want a row vector you need to add another layer of square brackets.

In [116]:
A=np.array([[4, 6, 8, 5, 1]])
print(A)

[[4 6 8 5 1]]


Observe that A is a a row of numbers.

Another type of 1D array is a column vector. Consider the following:

In [117]:
B=np.array([[4], [6], [8], [5], [1]])
print(B)

[[4]
 [6]
 [8]
 [5]
 [1]]


Note that the semicolons have made the vector into a column.

A row vector can be "transposed" into a column vector using `np.transpose`.

In [118]:
C=np.transpose(A)
print(C)

[[4]
 [6]
 [8]
 [5]
 [1]]


A row vector can be "transposed" into a column vector using `np.transpose`.

In [120]:
D=np.transpose(B)
print(D)

[[4 6 8 5 1]]


Arrays of the same size can be added (or subtracted) together.

In [121]:
print(A+D)

[[ 8 12 16 10  2]]


In [122]:
print(A-D)

[[0 0 0 0 0]]


These arrays can also be multiplied and divided by each other or even taken to the power of each other.

In [123]:
print(A*D)

[[16 36 64 25  1]]


In [124]:
print(A/D)

[[1. 1. 1. 1. 1.]]


In [126]:
print(A**D)

[[     256    46656 16777216     3125        1]]


However, the above operations are only possible when the arrays have the same size. The dimensions of an array can be checked using the size command.